#!/bin/bash
# script to build config.tar.xz after an update
# must be run in /home/robert/
cd /home/robert
tar --xz -C /home/robert -cvf config.tar.xz --exclude=*/storage --exclude=.local/share/.cpan .mozilla .bash_aliases .gitconfig .git-credentials .config .local
