#!/bin/bash
################################################
# configdata:postrm
################################################

# called with parameters remove or purge.
# only execute this script for removal
# when a purge is done, called with remove then with purge
test "$1" = "remove" || exit 0;

# console-setup is restored from the backup console-setup.bak
# if the backup exists, restore it
test -f "/etc/default/console-setup.bak" && cp -fv /etc/default/console-setup.bak /etc/default/console-setup

# restore console
setupcon -f
setupcon --save

# delete lines that were added to config.txt
/usr/bin/sed -i -e '/^# overclocking$/,/dtparam=fan_temp0_speed=/d' /boot/firmware/config.txt

# remove files from config.tar.xz
cd /home/robert
rm -rf .mozilla .config/ubuntu-mate .config/geany .config/dconf .config/gh .config/rclone .gitconfig .git-credentials

